### ISSUE TITLE
Error message displaying as null, when invalid, or incorrect number of arguments are supplied

### ISSUE THREAD

**Issue by ValliereMagic** [ValliereMagic/Centripetal_Physics_blarg#14]
Screenshot attached.
Occurred in orbital radius, unsure if occurs in other operations.
![untitled](https://cloud.githubusercontent.com/assets/20320239/23779901/4bdd4e98-0511-11e7-95fb-1494964d1dea.png)

**Comment by ValliereMagic** [comment]
I didn't choose the bug life, the bug life chose me.

**Comment by fradford** [comment]
See pull request #15 

Should be fixed there

**Comment by ValliereMagic** [comment]
Approved and merged.
