### ISSUE TITLE
Centripetal Acceleration mass and force gravity method

### ISSUE THREAD

**Issue by ValliereMagic** [ValliereMagic/Centripetal_Physics_blarg#16]
Just making sure that you meant force gravity and not centripetal force. I say this because my formula sheet says Fc = m(aC).

`static massAndForceGravity(double mass, double forceGravity) {
        return answerFormatter(forceGravity / mass)
    }`

**Comment by fradford** [comment]
Well, in this case at least the force of gravity is the same as the centripetal force. You could change the variable name if you wanted to but I'm pretty sure this one's mathematically sound.

**Comment by ValliereMagic** [comment]
Name updated for clarity and merged. #20
