### ISSUE TITLE
Radius Only method in centripetal acceleration

### ISSUE THREAD

**Issue by ValliereMagic** [ValliereMagic/Centripetal_Physics_blarg#17]
this is the logic i followed:
Fc = Fg
therefore (m)(aC) = ((G)(M)(m)) / r^2
Then the M's divide out leaving...
aC = ((G)(M)) / r^2
In the current code ...

`    static radiusOnly(double radius) {
        Main.earthAssumption()
        return answerFormatter((Main.gravityConstant * Main.cMassOfEarth) / radius)
    }`

The radius isn't squared... will wait for your comment before modifying code. To make sure you didn't do this on purpose or for another reason.

**Comment by fradford** [comment]
Looks like that's just an error on my part, I'm not sure where my notes went but just looking over it now maybe I got confused with velocity and radius or something, who knows. 

It should be fine to change that.

**Comment by fradford** [comment]
#19 should fix it

**Comment by ValliereMagic** [comment]
approved and merged.
